### ISSUE TITLE
Steps to enhance the user experience / user interface

### ISSUE THREAD

**Issue by Lewis-Hamilton** [KegenGuyll/DadJokes#8]
- [x] Add bootstrap to the application 
- [x] Create a color scheme
- [x] Decide a User Interface layout
- [x] Create a working prototype

**Comment by Lewis-Hamilton** [comment]
![Screen Shot 2019-07-10 at 9 42 00 AM](https://user-images.githubusercontent.com/38916472/60978622-07068380-a2f7-11e9-90a9-87404d6e92e9.png)

**Comment by Lewis-Hamilton** [comment]
<img width="253" alt="Screen Shot 2019-07-10 at 12 40 18 PM" src="https://user-images.githubusercontent.com/38916472/60991316-f1518800-a30f-11e9-9939-7de1acce3563.png">

**Comment by KegenGuyll** [comment]
Successfully merged
